Vagrant.configure("2") do |config|
  config.vm.hostname = "app01"
  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.1.3"
  config.vm.provision "shell", path: "provision.sh"
end